// src/lib/Aside.svelte
<script lang="ts">
  import IconArrowLeft from "./IconArrowLeft.svelte";

  const handleClick = () => {};
</script>

<aside class="fixed right-0">
  <button class="text-white absolute top-4 -left-4">
    <!-- <img class="text-white" src="/arrow-left-aside.svg" alt="" /> -->
    <IconArrowLeft isOpen={true} />
  </button>
  <button
    type="button"
    class="py-2.5 px-5 mr-2 mb-2 text-sm font-medium text-gray-900 focus:outline-none bg-white rounded-lg border border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700"
    on:click={handleClick}>Agregar</button
  >
</aside>

// src/components/Aside.vue
<script setup lang="ts">
import IconArrowLeftVue from "./IconArrowLeft.vue";

const isOpen: boolean = false;
const handleClick = () => {};
</script>

<template>
  <aside :class="`fixed ${isOpen ? 'right-0' : 'right-[0]'}`">
    <button class="text-white absolute top-4 -left-8">
      <!-- <img class="text-white" src="/arrow-left-aside.svg" alt="" /> -->
      <IconArrowLeftVue :isOpen="isOpen" />
    </button>
    <button
      type="button"
      class="py-2.5 px-5 mr-2 mb-2 text-sm font-medium text-gray-900 focus:outline-none bg-white rounded-lg border border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700"
      @click="handleClick"
    >
      Agregar
    </button>
  </aside>
</template>
