// src/components/CardBingoList.tsx
import { useGameStore } from "@/store/gameStore";
import { CardBingo } from "./CardBingo";

export function CardBingoList() {
  const cardList = useGameStore((state) => state.cardList);

  return (
    <section className="p-4 mt-4">
      <ul className="cardList-list">
        {cardList.length > 0 && (
          <>
            {cardList.map((card) => (
              <CardBingo numbers={card.data} key={card.bingo_card_id} />
            ))}
          </>
        )}
      </ul>
    </section>
  );
}

// src/components/CardBingoList.vue
<script setup lang="ts">
import { useCardsStore } from "../store/cardsStore";
import CardBingo from "./CardBingo.vue";
const { cardList } = useCardsStore();
</script>
<template>
  <section class="p-4 mt-4">
    <template v-if="cardList.length > 0">
      <ul class="cardList-list">
        <li v-for="card in cardList" class="cardList-item">
          <CardBingo :key="card.bingo_card_id" :numbers="card.data" />
        </li>
      </ul>
    </template>
    <h2 v-else class="text-white text-center text-3xl">No hay Tarjetas</h2>
  </section>
</template>
<style lang="postcss">
.cardList {
  &-list {
    @apply flex w-full;
    gap: 10px;
    scroll-snap-type: x mandatory;
    overflow-x: scroll;
    overflow-y: hidden;
  }
  &-item {
    scroll-snap-align: center;
    flex-shrink: 0;
  }
}
</style>
